export const CATEGORIES = [
    { key: 0, name: "Football", icon: "Football.svg" },
    { key: 1, name: "Basketball", icon: "Basketball.svg" },
    { key: 2, name: "Bodyweight", icon: "Bodyweight.svg" },
    { key: 3, name: "Boxing", icon: "Boxing.svg" },
    { key: 4, name: "Climbing", icon: "Climbing.svg" },
    { key: 5, name: "Dance", icon: "Dance.svg" },
    { key: 6, name: "Flexibility", icon: "Flexibility.svg" },
    { key: 7, name: "Yoga", icon: "Yoga.svg" },
    { key: 8, name: "Hiking", icon: "Hiking.svg" },
    { key: 9, name: "Lifting", icon: "Lifting.svg" },
    { key: 10, name: "Pilates", icon: "Pilates.svg" },
    { key: 11, name: "Sailing", icon: "Sailing.svg" },
    { key: 12, name: "Swimming", icon: "Swimming.svg" },
    { key: 13, name: "Tennis", icon: "Tennis.svg" },
    { key: 14, name: "Volleyball", icon: "Volleyball.svg" },
    { key: 15, name: "Water Polo", icon: "Water Polo.svg" },
];